
package todoApp.View;

import javax.swing.JOptionPane;
import todoApp.Controller.ProjectController;
import todoApp.Model.Project;

/**
 *
 * @author diegocarvalho
 */
public class ProjectDialogScreen extends javax.swing.JDialog {
    
    ProjectController controller;
    

    /**
     * Creates new form ProjectDialogScreen
     */
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjectController();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectBanner = new javax.swing.JPanel();
        pbTitle = new javax.swing.JLabel();
        pbIcon = new javax.swing.JLabel();
        projectPanel = new javax.swing.JPanel();
        ppName = new javax.swing.JLabel();
        ppNameField = new javax.swing.JTextField();
        ppDescription = new javax.swing.JLabel();
        ProjectScrolPanel = new javax.swing.JScrollPane();
        pspDescriptionField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ProjectBanner.setBackground(new java.awt.Color(0, 153, 102));

        pbTitle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        pbTitle.setForeground(new java.awt.Color(255, 255, 255));
        pbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pbTitle.setText("Projeto");

        pbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        pbIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProjectBannerLayout = new javax.swing.GroupLayout(ProjectBanner);
        ProjectBanner.setLayout(ProjectBannerLayout);
        ProjectBannerLayout.setHorizontalGroup(
            ProjectBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectBannerLayout.createSequentialGroup()
                .addComponent(pbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321)
                .addComponent(pbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProjectBannerLayout.setVerticalGroup(
            ProjectBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectBannerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ProjectBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        projectPanel.setBackground(new java.awt.Color(255, 255, 255));

        ppName.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        ppName.setForeground(new java.awt.Color(0, 0, 0));
        ppName.setText("Nome");

        ppNameField.setBackground(new java.awt.Color(255, 255, 255));
        ppNameField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        ppNameField.setForeground(new java.awt.Color(0, 0, 0));

        ppDescription.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        ppDescription.setForeground(new java.awt.Color(0, 0, 0));
        ppDescription.setText("Descrição");

        pspDescriptionField.setBackground(new java.awt.Color(255, 255, 255));
        pspDescriptionField.setColumns(20);
        pspDescriptionField.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        pspDescriptionField.setForeground(new java.awt.Color(0, 0, 0));
        pspDescriptionField.setRows(5);
        ProjectScrolPanel.setViewportView(pspDescriptionField);

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectScrolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(projectPanelLayout.createSequentialGroup()
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ppName)
                            .addComponent(ppDescription))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ppNameField))
                .addContainerGap())
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ppName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ppNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ppDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectScrolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pbIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbIconMouseClicked
         
        try {
            if (!ppNameField.getText().equals("")){
                Project project = new Project();
                project.setName(ppNameField.getText());
                project.setDescription(pspDescriptionField.getText());
                controller.save(project);
                JOptionPane.showMessageDialog(rootPane, "Projeto Cadastrado!");
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Deve preencher o campo Nome!");
                
            }
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            
        }
        
        this.dispose();
        
    }//GEN-LAST:event_pbIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProjectBanner;
    private javax.swing.JScrollPane ProjectScrolPanel;
    private javax.swing.JLabel pbIcon;
    private javax.swing.JLabel pbTitle;
    private javax.swing.JLabel ppDescription;
    private javax.swing.JLabel ppName;
    private javax.swing.JTextField ppNameField;
    private javax.swing.JPanel projectPanel;
    private javax.swing.JTextArea pspDescriptionField;
    // End of variables declaration//GEN-END:variables
}
